//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderAndStorageManagementSystem.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ( object.ReferenceEquals(resourceMan, null) )
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OrderAndStorageManagementSystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_add
        {
            get
            {
                object obj = ResourceManager.GetObject("img_add", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_1
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_1", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_10
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_10", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_11
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_11", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_12
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_12", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_13
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_13", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_14
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_14", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_15
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_15", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_16
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_16", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_17
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_17", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_18
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_18", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_19
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_19", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_2
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_2", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_20
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_20", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_21
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_21", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_22
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_22", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_23
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_23", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_24
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_24", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_25
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_25", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_26
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_26", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_27
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_27", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_28
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_28", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_29
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_29", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_3
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_3", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_30
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_30", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_31
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_31", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_32
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_32", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_33
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_33", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_34
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_34", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_4
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_4", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_5
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_5", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_6
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_6", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_7
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_7", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_8
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_8", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_AppDatabase_ProductsTable_9
        {
            get
            {
                object obj = ResourceManager.GetObject("img_AppDatabase_ProductsTable_9", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_delivery_truck
        {
            get
            {
                object obj = ResourceManager.GetObject("img_delivery_truck", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_left_arrow
        {
            get
            {
                object obj = ResourceManager.GetObject("img_left_arrow", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_right_arrow
        {
            get
            {
                object obj = ResourceManager.GetObject("img_right_arrow", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap img_trash_bin
        {
            get
            {
                object obj = ResourceManager.GetObject("img_trash_bin", resourceCulture);
                return ( ( System.Drawing.Bitmap )( obj ) );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ProductId,ProductName,ProductType,ProductPrice,ProductStorageQuantity,ProductDescription
        ///1,技嘉 GA-E3000N 主機板,主機板,1490,10,&quot;內建雙核心AMD E2-3000 及Radeon™ HD 8280內建顯示處理器|2組DDR3插槽，支援單通道技術及Non-ECC記憶體|顯示輸出:1 x HDMI,1 x D-Sub|PCB規格:Mini-ITX|&quot;
        ///2,華碩 STRIX Z390-E GAMING 主機板,主機板,7090,20,AI智能超頻，主動判斷CPU體質與散熱條件，提供客製化的最佳超頻設定|OPTIMEM II技術 支援4DIMM DDR4超頻4266，相容性穩定性最佳|DRMOS技術、PROCOOL實心電源接頭、提供最佳超頻電源供應|預裝式IO檔板，IO COVER含AURA燈光效果|支援AURA SYNC RGB同步燈效、3*RGB針腳|2*4Pin+1*3PIN可編成)|內建INTEL CNVI 2T2R AC WIFI+BT5.0|雙M.2散熱模組確實降低M.2溫度|Supreme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ProductsTable
        {
            get
            {
                return ResourceManager.GetString("ProductsTable", resourceCulture);
            }
        }
    }
}
